ALTER TYPE "NotificationType" ADD VALUE 'PARTNER_REQUEST_RECEIVED';
ALTER TYPE "NotificationType" ADD VALUE 'PARTNER_REQUEST_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE 'PARTNER_REQUEST_REJECTED';
